# Generated by Django 4.0.4 on 2022-05-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonhistory',
            name='grade',
            field=models.FloatField(blank=True, help_text='grade for this lesson history.', null=True),
        ),
    ]
