# Generated by Django 4.0.4 on 2022-05-30 16:33

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioninfo',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='transactioninfo',
            name='details',
            field=common.fields.DataclassJSONField(blank=True, help_text='Transaction details', null=True),
        ),
    ]
