# Generated by Django 4.0.4 on 2022-05-23 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Used in the lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.lessonhistory'),
        ),
    ]
