# Generated by Django 4.0.4 on 2022-05-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lessonhistory_grade'),
        ('booking', '0002_bookingrecord_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrecord',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Used in the lesson', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lessonhistory'),
        ),
    ]
