# Generated by Django 4.0.4 on 2022-05-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
