# Generated by Django 4.0.4 on 2022-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='status',
            new_name='progress',
        ),
        migrations.AddField(
            model_name='maintenancerecorditem',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
    ]
