# Generated by Django 4.0.4 on 2022-05-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_alter_plane_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='plane.plane'),
        ),
        migrations.AlterField(
            model_name='maintenancerecorditem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecorditem',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecorditem',
            name='maintenance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plane.maintenancerecord'),
        ),
    ]
