# Generated by Django 4.0.4 on 2022-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0003_alter_maintenancerecord_plane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecorditem',
            name='status',
            field=models.CharField(choices=[('GOOD_CONDITION', 'good'), ('BAD_CONDITION', 'bad')], default='GOOD_CONDITION', max_length=128),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='progress',
            field=models.CharField(choices=[('PENDING', 'pending'), ('IN_PROGRESS', 'in progress'), ('FINISHED', 'finished')], default='PENDING', max_length=128),
        ),
    ]
