# Generated by Django 4.0.4 on 2022-05-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0004_maintenancerecorditem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='progress',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='PENDING', max_length=128),
        ),
        migrations.AlterField(
            model_name='maintenancerecorditem',
            name='status',
            field=models.CharField(choices=[('GOOD_CONDITION', 'Good Condition'), ('BAD_CONDITION', 'Bad Condition'), ('EXPIRED', 'Expired')], default='GOOD_CONDITION', max_length=128),
        ),
    ]
