name: Build Docker Image

on:
  push:
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements.txt
        run: pip3 install -r requirements.txt
      - name: Check outdated dependencies
        run: pip3 list --outdated
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements.txt
        run: pip3 install -r requirements.txt
      - name: Test
        run: python3 manage.py test

